// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/core/v1/events.proto

package core

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_ETYPE_UNKONWN  EventType = 0
	EventType_ETYPE_STARTED  EventType = 1
	EventType_ETYPE_FINISHED EventType = 2
	EventType_ETYPE_QUEUED   EventType = 3
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "ETYPE_UNKONWN",
		1: "ETYPE_STARTED",
		2: "ETYPE_FINISHED",
		3: "ETYPE_QUEUED",
	}
	EventType_value = map[string]int32{
		"ETYPE_UNKONWN":  0,
		"ETYPE_STARTED":  1,
		"ETYPE_FINISHED": 2,
		"ETYPE_QUEUED":   3,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_carabiner_core_v1_events_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_carabiner_core_v1_events_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_carabiner_core_v1_events_proto_rawDescGZIP(), []int{0}
}

// PipelineRun is captures the data of a pipeline execution
type PipelineRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=carabiner.core.v1.EventType" json:"type,omitempty"`
	Pipeline      *Pipeline              `protobuf:"bytes,2,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PipelineRun) Reset() {
	*x = PipelineRun{}
	mi := &file_carabiner_core_v1_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PipelineRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PipelineRun) ProtoMessage() {}

func (x *PipelineRun) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PipelineRun.ProtoReflect.Descriptor instead.
func (*PipelineRun) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_events_proto_rawDescGZIP(), []int{0}
}

func (x *PipelineRun) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_ETYPE_UNKONWN
}

func (x *PipelineRun) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

func (x *PipelineRun) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PipelineRun) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *PipelineRun) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

// StepRun captures the information of a step execution
type StepRun struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=carabiner.core.v1.EventType" json:"type,omitempty"`
	Step          *Step                  `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	PipelineRun   *PipelineRun           `protobuf:"bytes,3,opt,name=pipeline_run,json=pipelineRun,proto3" json:"pipeline_run,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Payload       *structpb.Struct       `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StepRun) Reset() {
	*x = StepRun{}
	mi := &file_carabiner_core_v1_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StepRun) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StepRun) ProtoMessage() {}

func (x *StepRun) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StepRun.ProtoReflect.Descriptor instead.
func (*StepRun) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_events_proto_rawDescGZIP(), []int{1}
}

func (x *StepRun) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_ETYPE_UNKONWN
}

func (x *StepRun) GetStep() *Step {
	if x != nil {
		return x.Step
	}
	return nil
}

func (x *StepRun) GetPipelineRun() *PipelineRun {
	if x != nil {
		return x.PipelineRun
	}
	return nil
}

func (x *StepRun) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *StepRun) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

var file_carabiner_core_v1_events_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.EnumValueOptions)(nil),
		ExtensionType: (*string)(nil),
		Field:         42445,
		Name:          "carabiner.core.v1.name",
		Tag:           "bytes,42445,opt,name=name",
		Filename:      "carabiner/core/v1/events.proto",
	},
}

// Extension fields to descriptorpb.EnumValueOptions.
var (
	// optional string name = 42445;
	E_Name = &file_carabiner_core_v1_events_proto_extTypes[0]
)

var File_carabiner_core_v1_events_proto protoreflect.FileDescriptor

const file_carabiner_core_v1_events_proto_rawDesc = "" +
	"\n" +
	"\x1ecarabiner/core/v1/events.proto\x12\x11carabiner.core.v1\x1a\x1fcarabiner/core/v1/objects.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a google/protobuf/descriptor.proto\"\x94\x02\n" +
	"\vPipelineRun\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.carabiner.core.v1.EventTypeR\x04type\x127\n" +
	"\bpipeline\x18\x02 \x01(\v2\x1b.carabiner.core.v1.PipelineR\bpipeline\x12-\n" +
	"\x04name\x18\x03 \x01(\tB\x19\xbaH\x16r\x14\x18\xc8\x012\x0f^[-_a-zA-Z0-9]$R\x04name\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload\"\x98\x02\n" +
	"\aStepRun\x120\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1c.carabiner.core.v1.EventTypeR\x04type\x12+\n" +
	"\x04step\x18\x02 \x01(\v2\x17.carabiner.core.v1.StepR\x04step\x12A\n" +
	"\fpipeline_run\x18\x03 \x01(\v2\x1e.carabiner.core.v1.PipelineRunR\vpipelineRun\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x121\n" +
	"\apayload\x18\x05 \x01(\v2\x17.google.protobuf.StructR\apayload*~\n" +
	"\tEventType\x12\x11\n" +
	"\rETYPE_UNKONWN\x10\x00\x12\x1e\n" +
	"\rETYPE_STARTED\x10\x01\x1a\v\xea\xdc\x14\astarted\x12 \n" +
	"\x0eETYPE_FINISHED\x10\x02\x1a\f\xea\xdc\x14\bfinished\x12\x1c\n" +
	"\fETYPE_QUEUED\x10\x03\x1a\n" +
	"\xea\xdc\x14\x06queued::\n" +
	"\x04name\x12!.google.protobuf.EnumValueOptions\x18\xcd\xcb\x02 \x01(\tR\x04name\x88\x01\x01B\xc4\x01\n" +
	"\x15com.carabiner.core.v1B\vEventsProtoP\x01Z8github.com/carabiner-dev/core/api/carabiner/core/v1;core\xa2\x02\x03CCX\xaa\x02\x11Carabiner.Core.V1\xca\x02\x11Carabiner\\Core\\V1\xe2\x02\x1dCarabiner\\Core\\V1\\GPBMetadata\xea\x02\x13Carabiner::Core::V1b\x06proto3"

var (
	file_carabiner_core_v1_events_proto_rawDescOnce sync.Once
	file_carabiner_core_v1_events_proto_rawDescData []byte
)

func file_carabiner_core_v1_events_proto_rawDescGZIP() []byte {
	file_carabiner_core_v1_events_proto_rawDescOnce.Do(func() {
		file_carabiner_core_v1_events_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_events_proto_rawDesc), len(file_carabiner_core_v1_events_proto_rawDesc)))
	})
	return file_carabiner_core_v1_events_proto_rawDescData
}

var file_carabiner_core_v1_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_carabiner_core_v1_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_carabiner_core_v1_events_proto_goTypes = []any{
	(EventType)(0),                        // 0: carabiner.core.v1.EventType
	(*PipelineRun)(nil),                   // 1: carabiner.core.v1.PipelineRun
	(*StepRun)(nil),                       // 2: carabiner.core.v1.StepRun
	(*Pipeline)(nil),                      // 3: carabiner.core.v1.Pipeline
	(*timestamppb.Timestamp)(nil),         // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),               // 5: google.protobuf.Struct
	(*Step)(nil),                          // 6: carabiner.core.v1.Step
	(*descriptorpb.EnumValueOptions)(nil), // 7: google.protobuf.EnumValueOptions
}
var file_carabiner_core_v1_events_proto_depIdxs = []int32{
	0,  // 0: carabiner.core.v1.PipelineRun.type:type_name -> carabiner.core.v1.EventType
	3,  // 1: carabiner.core.v1.PipelineRun.pipeline:type_name -> carabiner.core.v1.Pipeline
	4,  // 2: carabiner.core.v1.PipelineRun.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 3: carabiner.core.v1.PipelineRun.payload:type_name -> google.protobuf.Struct
	0,  // 4: carabiner.core.v1.StepRun.type:type_name -> carabiner.core.v1.EventType
	6,  // 5: carabiner.core.v1.StepRun.step:type_name -> carabiner.core.v1.Step
	1,  // 6: carabiner.core.v1.StepRun.pipeline_run:type_name -> carabiner.core.v1.PipelineRun
	4,  // 7: carabiner.core.v1.StepRun.timestamp:type_name -> google.protobuf.Timestamp
	5,  // 8: carabiner.core.v1.StepRun.payload:type_name -> google.protobuf.Struct
	7,  // 9: carabiner.core.v1.name:extendee -> google.protobuf.EnumValueOptions
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	9,  // [9:10] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_carabiner_core_v1_events_proto_init() }
func file_carabiner_core_v1_events_proto_init() {
	if File_carabiner_core_v1_events_proto != nil {
		return
	}
	file_carabiner_core_v1_objects_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_events_proto_rawDesc), len(file_carabiner_core_v1_events_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 1,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_core_v1_events_proto_goTypes,
		DependencyIndexes: file_carabiner_core_v1_events_proto_depIdxs,
		EnumInfos:         file_carabiner_core_v1_events_proto_enumTypes,
		MessageInfos:      file_carabiner_core_v1_events_proto_msgTypes,
		ExtensionInfos:    file_carabiner_core_v1_events_proto_extTypes,
	}.Build()
	File_carabiner_core_v1_events_proto = out.File
	file_carabiner_core_v1_events_proto_goTypes = nil
	file_carabiner_core_v1_events_proto_depIdxs = nil
}
