// SPDX-FileCopyrightText: Copyright 2026 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: carabiner/core/v1/labels.proto

package core

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LabelOperator is how a LabelRequirement relates a key to its values.
type LabelOperator int32

const (
	// Unspecified; invalid in a requirement.
	LabelOperator_LABEL_OPERATOR_UNSPECIFIED LabelOperator = 0
	// The key is set and its value is one of values.
	LabelOperator_LABEL_OPERATOR_IN LabelOperator = 1
	// The key is not set, or its value is none of values.
	LabelOperator_LABEL_OPERATOR_NOT_IN LabelOperator = 2
	// The key is set, with any value.
	LabelOperator_LABEL_OPERATOR_EXISTS LabelOperator = 3
	// The key is not set.
	LabelOperator_LABEL_OPERATOR_DOES_NOT_EXIST LabelOperator = 4
)

// Enum value maps for LabelOperator.
var (
	LabelOperator_name = map[int32]string{
		0: "LABEL_OPERATOR_UNSPECIFIED",
		1: "LABEL_OPERATOR_IN",
		2: "LABEL_OPERATOR_NOT_IN",
		3: "LABEL_OPERATOR_EXISTS",
		4: "LABEL_OPERATOR_DOES_NOT_EXIST",
	}
	LabelOperator_value = map[string]int32{
		"LABEL_OPERATOR_UNSPECIFIED":    0,
		"LABEL_OPERATOR_IN":             1,
		"LABEL_OPERATOR_NOT_IN":         2,
		"LABEL_OPERATOR_EXISTS":         3,
		"LABEL_OPERATOR_DOES_NOT_EXIST": 4,
	}
)

func (x LabelOperator) Enum() *LabelOperator {
	p := new(LabelOperator)
	*p = x
	return p
}

func (x LabelOperator) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LabelOperator) Descriptor() protoreflect.EnumDescriptor {
	return file_carabiner_core_v1_labels_proto_enumTypes[0].Descriptor()
}

func (LabelOperator) Type() protoreflect.EnumType {
	return &file_carabiner_core_v1_labels_proto_enumTypes[0]
}

func (x LabelOperator) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LabelOperator.Descriptor instead.
func (LabelOperator) EnumDescriptor() ([]byte, []int) {
	return file_carabiner_core_v1_labels_proto_rawDescGZIP(), []int{0}
}

// LabelSelector selects resources by their effective labels. All of
// match_labels and all of match_expressions must hold. A selector with
// neither is invalid and matches nothing: selecting every resource has to be
// said outright, never by leaving a selector empty.
type LabelSelector struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// match_labels requires each key to be set with exactly this value. An
	// empty value requires the key to be set with an empty value.
	MatchLabels map[string]string `protobuf:"bytes,1,rep,name=match_labels,json=matchLabels,proto3" json:"match_labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// match_expressions are further requirements, all of which must hold.
	MatchExpressions []*LabelRequirement `protobuf:"bytes,2,rep,name=match_expressions,json=matchExpressions,proto3" json:"match_expressions,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LabelSelector) Reset() {
	*x = LabelSelector{}
	mi := &file_carabiner_core_v1_labels_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelSelector) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelSelector) ProtoMessage() {}

func (x *LabelSelector) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_labels_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelSelector.ProtoReflect.Descriptor instead.
func (*LabelSelector) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_labels_proto_rawDescGZIP(), []int{0}
}

func (x *LabelSelector) GetMatchLabels() map[string]string {
	if x != nil {
		return x.MatchLabels
	}
	return nil
}

func (x *LabelSelector) GetMatchExpressions() []*LabelRequirement {
	if x != nil {
		return x.MatchExpressions
	}
	return nil
}

// LabelRequirement is one condition on a label key.
type LabelRequirement struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// key is the label key the requirement is about.
	Key string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	// operator relates the key to values.
	Operator LabelOperator `protobuf:"varint,2,opt,name=operator,proto3,enum=carabiner.core.v1.LabelOperator" json:"operator,omitempty"`
	// values are the values for LABEL_OPERATOR_IN and LABEL_OPERATOR_NOT_IN
	// (at least one). They must be empty for the other operators.
	Values        []string `protobuf:"bytes,3,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LabelRequirement) Reset() {
	*x = LabelRequirement{}
	mi := &file_carabiner_core_v1_labels_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LabelRequirement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LabelRequirement) ProtoMessage() {}

func (x *LabelRequirement) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_labels_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LabelRequirement.ProtoReflect.Descriptor instead.
func (*LabelRequirement) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_labels_proto_rawDescGZIP(), []int{1}
}

func (x *LabelRequirement) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LabelRequirement) GetOperator() LabelOperator {
	if x != nil {
		return x.Operator
	}
	return LabelOperator_LABEL_OPERATOR_UNSPECIFIED
}

func (x *LabelRequirement) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_carabiner_core_v1_labels_proto protoreflect.FileDescriptor

const file_carabiner_core_v1_labels_proto_rawDesc = "" +
	"\n" +
	"\x1ecarabiner/core/v1/labels.proto\x12\x11carabiner.core.v1\"\xf7\x01\n" +
	"\rLabelSelector\x12T\n" +
	"\fmatch_labels\x18\x01 \x03(\v21.carabiner.core.v1.LabelSelector.MatchLabelsEntryR\vmatchLabels\x12P\n" +
	"\x11match_expressions\x18\x02 \x03(\v2#.carabiner.core.v1.LabelRequirementR\x10matchExpressions\x1a>\n" +
	"\x10MatchLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"z\n" +
	"\x10LabelRequirement\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12<\n" +
	"\boperator\x18\x02 \x01(\x0e2 .carabiner.core.v1.LabelOperatorR\boperator\x12\x16\n" +
	"\x06values\x18\x03 \x03(\tR\x06values*\x9f\x01\n" +
	"\rLabelOperator\x12\x1e\n" +
	"\x1aLABEL_OPERATOR_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11LABEL_OPERATOR_IN\x10\x01\x12\x19\n" +
	"\x15LABEL_OPERATOR_NOT_IN\x10\x02\x12\x19\n" +
	"\x15LABEL_OPERATOR_EXISTS\x10\x03\x12!\n" +
	"\x1dLABEL_OPERATOR_DOES_NOT_EXIST\x10\x04B\xc4\x01\n" +
	"\x15com.carabiner.core.v1B\vLabelsProtoP\x01Z8github.com/carabiner-dev/core/api/carabiner/core/v1;core\xa2\x02\x03CCX\xaa\x02\x11Carabiner.Core.V1\xca\x02\x11Carabiner\\Core\\V1\xe2\x02\x1dCarabiner\\Core\\V1\\GPBMetadata\xea\x02\x13Carabiner::Core::V1b\x06proto3"

var (
	file_carabiner_core_v1_labels_proto_rawDescOnce sync.Once
	file_carabiner_core_v1_labels_proto_rawDescData []byte
)

func file_carabiner_core_v1_labels_proto_rawDescGZIP() []byte {
	file_carabiner_core_v1_labels_proto_rawDescOnce.Do(func() {
		file_carabiner_core_v1_labels_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_labels_proto_rawDesc), len(file_carabiner_core_v1_labels_proto_rawDesc)))
	})
	return file_carabiner_core_v1_labels_proto_rawDescData
}

var file_carabiner_core_v1_labels_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_carabiner_core_v1_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_carabiner_core_v1_labels_proto_goTypes = []any{
	(LabelOperator)(0),       // 0: carabiner.core.v1.LabelOperator
	(*LabelSelector)(nil),    // 1: carabiner.core.v1.LabelSelector
	(*LabelRequirement)(nil), // 2: carabiner.core.v1.LabelRequirement
	nil,                      // 3: carabiner.core.v1.LabelSelector.MatchLabelsEntry
}
var file_carabiner_core_v1_labels_proto_depIdxs = []int32{
	3, // 0: carabiner.core.v1.LabelSelector.match_labels:type_name -> carabiner.core.v1.LabelSelector.MatchLabelsEntry
	2, // 1: carabiner.core.v1.LabelSelector.match_expressions:type_name -> carabiner.core.v1.LabelRequirement
	0, // 2: carabiner.core.v1.LabelRequirement.operator:type_name -> carabiner.core.v1.LabelOperator
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_carabiner_core_v1_labels_proto_init() }
func file_carabiner_core_v1_labels_proto_init() {
	if File_carabiner_core_v1_labels_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_labels_proto_rawDesc), len(file_carabiner_core_v1_labels_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_core_v1_labels_proto_goTypes,
		DependencyIndexes: file_carabiner_core_v1_labels_proto_depIdxs,
		EnumInfos:         file_carabiner_core_v1_labels_proto_enumTypes,
		MessageInfos:      file_carabiner_core_v1_labels_proto_msgTypes,
	}.Build()
	File_carabiner_core_v1_labels_proto = out.File
	file_carabiner_core_v1_labels_proto_goTypes = nil
	file_carabiner_core_v1_labels_proto_depIdxs = nil
}
