// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/core/v1/objects.proto

package core

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// A system abstracts a system capable of handling one or more stages
// of the SDLC. A CI/CD system, for example, can handle builds
type System struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Type          string                 `protobuf:"bytes,3,opt,name=Type,proto3" json:"Type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *System) Reset() {
	*x = System{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{0}
}

func (x *System) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *System) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *System) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Namespace abstracts a namespace inside of a system
type Namespace struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	System        *System                `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{1}
}

func (x *Namespace) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Namespace) GetSystem() *System {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Pipeline abstracts a collection of steps
type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{2}
}

func (x *Pipeline) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// Step is a CI/CD operation part of a pipeline
type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pipeline      *Pipeline              `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{3}
}

func (x *Step) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

var File_carabiner_core_v1_objects_proto protoreflect.FileDescriptor

const file_carabiner_core_v1_objects_proto_rawDesc = "" +
	"\n" +
	"\x1fcarabiner/core/v1/objects.proto\x12\x11carabiner.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"a\n" +
	"\x06System\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x12\x12\n" +
	"\x04Name\x18\x02 \x01(\tR\x04Name\x12)\n" +
	"\x04Type\x18\x03 \x01(\tB\x15\xbaH\x12r\x10R\x06githubR\x06gitlabR\x04Type\"\x87\x01\n" +
	"\tNamespace\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x121\n" +
	"\x06system\x18\x02 \x01(\v2\x19.carabiner.core.v1.SystemR\x06system\x12-\n" +
	"\x04name\x18\x03 \x01(\tB\x19\xbaH\x16r\x14\x18\xc8\x012\x0f^[-_a-zA-Z0-9]$R\x04name\"S\n" +
	"\bPipeline\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x12-\n" +
	"\x04name\x18\x02 \x01(\tB\x19\xbaH\x16r\x14\x18\xc8\x012\x0f^[-_a-zA-Z0-9]$R\x04name\"\x88\x01\n" +
	"\x04Step\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x12-\n" +
	"\x04name\x18\x02 \x01(\tB\x19\xbaH\x16r\x14\x18\xc8\x012\x0f^[-_a-zA-Z0-9]$R\x04name\x127\n" +
	"\bpipeline\x18\x03 \x01(\v2\x1b.carabiner.core.v1.PipelineR\bpipelineB\xc5\x01\n" +
	"\x15com.carabiner.core.v1B\fObjectsProtoP\x01Z8github.com/carabiner-dev/core/api/carabiner/core/v1;core\xa2\x02\x03CCX\xaa\x02\x11Carabiner.Core.V1\xca\x02\x11Carabiner\\Core\\V1\xe2\x02\x1dCarabiner\\Core\\V1\\GPBMetadata\xea\x02\x13Carabiner::Core::V1b\x06proto3"

var (
	file_carabiner_core_v1_objects_proto_rawDescOnce sync.Once
	file_carabiner_core_v1_objects_proto_rawDescData []byte
)

func file_carabiner_core_v1_objects_proto_rawDescGZIP() []byte {
	file_carabiner_core_v1_objects_proto_rawDescOnce.Do(func() {
		file_carabiner_core_v1_objects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_objects_proto_rawDesc), len(file_carabiner_core_v1_objects_proto_rawDesc)))
	})
	return file_carabiner_core_v1_objects_proto_rawDescData
}

var file_carabiner_core_v1_objects_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_carabiner_core_v1_objects_proto_goTypes = []any{
	(*System)(nil),    // 0: carabiner.core.v1.System
	(*Namespace)(nil), // 1: carabiner.core.v1.Namespace
	(*Pipeline)(nil),  // 2: carabiner.core.v1.Pipeline
	(*Step)(nil),      // 3: carabiner.core.v1.Step
}
var file_carabiner_core_v1_objects_proto_depIdxs = []int32{
	0, // 0: carabiner.core.v1.Namespace.system:type_name -> carabiner.core.v1.System
	2, // 1: carabiner.core.v1.Step.pipeline:type_name -> carabiner.core.v1.Pipeline
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_carabiner_core_v1_objects_proto_init() }
func file_carabiner_core_v1_objects_proto_init() {
	if File_carabiner_core_v1_objects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_objects_proto_rawDesc), len(file_carabiner_core_v1_objects_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_core_v1_objects_proto_goTypes,
		DependencyIndexes: file_carabiner_core_v1_objects_proto_depIdxs,
		MessageInfos:      file_carabiner_core_v1_objects_proto_msgTypes,
	}.Build()
	File_carabiner_core_v1_objects_proto = out.File
	file_carabiner_core_v1_objects_proto_goTypes = nil
	file_carabiner_core_v1_objects_proto_depIdxs = nil
}
