// SPDX-FileCopyrightText: Copyright 2025 Carabiner Systems, Inc
// SPDX-License-Identifier: Apache-2.0

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: carabiner/core/v1/objects.proto

package core

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Status represents the lifecycle state of a resource. STATUS_UNSPECIFIED is
// treated as STATUS_ACTIVE for backward compatibility with records written
// before the field existed.
type Status int32

const (
	Status_STATUS_UNSPECIFIED Status = 0
	Status_STATUS_ACTIVE      Status = 1
	Status_STATUS_SUSPENDED   Status = 2
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_ACTIVE",
		2: "STATUS_SUSPENDED",
	}
	Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_ACTIVE":      1,
		"STATUS_SUSPENDED":   2,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_carabiner_core_v1_objects_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_carabiner_core_v1_objects_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{0}
}

// A system abstracts a system capable of handling one or more stages
// of the SDLC. A CI/CD system, for example, can handle builds
type System struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Organization  string                 `protobuf:"bytes,2,opt,name=organization,proto3" json:"organization,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *System) Reset() {
	*x = System{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *System) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*System) ProtoMessage() {}

func (x *System) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use System.ProtoReflect.Descriptor instead.
func (*System) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{0}
}

func (x *System) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *System) GetOrganization() string {
	if x != nil {
		return x.Organization
	}
	return ""
}

func (x *System) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *System) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Namespace abstracts a namespace inside of a system
type Namespace struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	ID     string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	System *System                `protobuf:"bytes,2,opt,name=system,proto3" json:"system,omitempty"`
	Name   string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// Lifecycle status. Set to STATUS_SUSPENDED when the backing GitHub App
	// installation is suspended. Unspecified is treated as active.
	Status        Status `protobuf:"varint,4,opt,name=status,proto3,enum=carabiner.core.v1.Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Namespace) Reset() {
	*x = Namespace{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Namespace) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Namespace) ProtoMessage() {}

func (x *Namespace) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Namespace.ProtoReflect.Descriptor instead.
func (*Namespace) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{1}
}

func (x *Namespace) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Namespace) GetSystem() *System {
	if x != nil {
		return x.System
	}
	return nil
}

func (x *Namespace) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Namespace) GetStatus() Status {
	if x != nil {
		return x.Status
	}
	return Status_STATUS_UNSPECIFIED
}

// Repository abstracts a source-code repository tracked under a namespace. The
// descriptive fields below are populated from the source system when the
// repository is connected (registered). They are system-agnostic so any system
// (GitHub, GitLab, …) maps onto them.
type Repository struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ID        string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name      string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Namespace *Namespace             `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// external_id is the repository's stable identifier in its source system
	// (e.g. a GitHub numeric repository ID). It is immutable across renames and
	// is the idempotency/lookup key for a connected repository.
	ExternalId string `protobuf:"bytes,4,opt,name=external_id,json=externalId,proto3" json:"external_id,omitempty"`
	// slug is the repository's human-readable path within its system, e.g.
	// "owner/repo". It is mutable: a rename changes the slug but not external_id.
	Slug string `protobuf:"bytes,5,opt,name=slug,proto3" json:"slug,omitempty"`
	// url is the repository's web URL.
	Url string `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	// visibility is the repository's visibility in its system, e.g. "public",
	// "private", or "internal".
	Visibility string `protobuf:"bytes,7,opt,name=visibility,proto3" json:"visibility,omitempty"`
	// default_branch is the repository's default branch, e.g. "main".
	DefaultBranch string `protobuf:"bytes,8,opt,name=default_branch,json=defaultBranch,proto3" json:"default_branch,omitempty"`
	// description is the repository's short description.
	Description   string `protobuf:"bytes,9,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Repository) Reset() {
	*x = Repository{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Repository) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Repository) ProtoMessage() {}

func (x *Repository) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Repository.ProtoReflect.Descriptor instead.
func (*Repository) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{2}
}

func (x *Repository) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Repository) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Repository) GetNamespace() *Namespace {
	if x != nil {
		return x.Namespace
	}
	return nil
}

func (x *Repository) GetExternalId() string {
	if x != nil {
		return x.ExternalId
	}
	return ""
}

func (x *Repository) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *Repository) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Repository) GetVisibility() string {
	if x != nil {
		return x.Visibility
	}
	return ""
}

func (x *Repository) GetDefaultBranch() string {
	if x != nil {
		return x.DefaultBranch
	}
	return ""
}

func (x *Repository) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// Pipeline abstracts a collection of steps
type Pipeline struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Repository    *Repository            `protobuf:"bytes,3,opt,name=repository,proto3" json:"repository,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Pipeline) Reset() {
	*x = Pipeline{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pipeline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pipeline) ProtoMessage() {}

func (x *Pipeline) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pipeline.ProtoReflect.Descriptor instead.
func (*Pipeline) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{3}
}

func (x *Pipeline) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Pipeline) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Pipeline) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

// Step is a CI/CD operation part of a pipeline
type Step struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ID            string                 `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Pipeline      *Pipeline              `protobuf:"bytes,3,opt,name=pipeline,proto3" json:"pipeline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Step) Reset() {
	*x = Step{}
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Step) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Step) ProtoMessage() {}

func (x *Step) ProtoReflect() protoreflect.Message {
	mi := &file_carabiner_core_v1_objects_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Step.ProtoReflect.Descriptor instead.
func (*Step) Descriptor() ([]byte, []int) {
	return file_carabiner_core_v1_objects_proto_rawDescGZIP(), []int{4}
}

func (x *Step) GetID() string {
	if x != nil {
		return x.ID
	}
	return ""
}

func (x *Step) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Step) GetPipeline() *Pipeline {
	if x != nil {
		return x.Pipeline
	}
	return nil
}

var File_carabiner_core_v1_objects_proto protoreflect.FileDescriptor

const file_carabiner_core_v1_objects_proto_rawDesc = "" +
	"\n" +
	"\x1fcarabiner/core/v1/objects.proto\x12\x11carabiner.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bbuf/validate/validate.proto\"\x85\x01\n" +
	"\x06System\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x12\"\n" +
	"\forganization\x18\x02 \x01(\tR\forganization\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12)\n" +
	"\x04type\x18\x04 \x01(\tB\x15\xbaH\x12r\x10R\x06githubR\x06gitlabR\x04type\"\xbb\x01\n" +
	"\tNamespace\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x121\n" +
	"\x06system\x18\x02 \x01(\v2\x19.carabiner.core.v1.SystemR\x06system\x12.\n" +
	"\x04name\x18\x03 \x01(\tB\x1a\xbaH\x17r\x15\x18\xc8\x012\x10^[-_a-zA-Z0-9]+$R\x04name\x121\n" +
	"\x06status\x18\x04 \x01(\x0e2\x19.carabiner.core.v1.StatusR\x06status\"\xc2\x02\n" +
	"\n" +
	"Repository\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x12.\n" +
	"\x04name\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\x18\xc8\x012\x10^[-_a-zA-Z0-9]+$R\x04name\x12:\n" +
	"\tnamespace\x18\x03 \x01(\v2\x1c.carabiner.core.v1.NamespaceR\tnamespace\x12\x1f\n" +
	"\vexternal_id\x18\x04 \x01(\tR\n" +
	"externalId\x12\x12\n" +
	"\x04slug\x18\x05 \x01(\tR\x04slug\x12\x10\n" +
	"\x03url\x18\x06 \x01(\tR\x03url\x12\x1e\n" +
	"\n" +
	"visibility\x18\a \x01(\tR\n" +
	"visibility\x12%\n" +
	"\x0edefault_branch\x18\b \x01(\tR\rdefaultBranch\x12 \n" +
	"\vdescription\x18\t \x01(\tR\vdescription\"\x93\x01\n" +
	"\bPipeline\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x12.\n" +
	"\x04name\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\x18\xc8\x012\x10^[-_a-zA-Z0-9]+$R\x04name\x12=\n" +
	"\n" +
	"repository\x18\x03 \x01(\v2\x1d.carabiner.core.v1.RepositoryR\n" +
	"repository\"\x89\x01\n" +
	"\x04Step\x12\x18\n" +
	"\x02ID\x18\x01 \x01(\tB\b\xbaH\x05r\x03\xb0\x01\x01R\x02ID\x12.\n" +
	"\x04name\x18\x02 \x01(\tB\x1a\xbaH\x17r\x15\x18\xc8\x012\x10^[-_a-zA-Z0-9]+$R\x04name\x127\n" +
	"\bpipeline\x18\x03 \x01(\v2\x1b.carabiner.core.v1.PipelineR\bpipeline*I\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rSTATUS_ACTIVE\x10\x01\x12\x14\n" +
	"\x10STATUS_SUSPENDED\x10\x02B\xc5\x01\n" +
	"\x15com.carabiner.core.v1B\fObjectsProtoP\x01Z8github.com/carabiner-dev/core/api/carabiner/core/v1;core\xa2\x02\x03CCX\xaa\x02\x11Carabiner.Core.V1\xca\x02\x11Carabiner\\Core\\V1\xe2\x02\x1dCarabiner\\Core\\V1\\GPBMetadata\xea\x02\x13Carabiner::Core::V1b\x06proto3"

var (
	file_carabiner_core_v1_objects_proto_rawDescOnce sync.Once
	file_carabiner_core_v1_objects_proto_rawDescData []byte
)

func file_carabiner_core_v1_objects_proto_rawDescGZIP() []byte {
	file_carabiner_core_v1_objects_proto_rawDescOnce.Do(func() {
		file_carabiner_core_v1_objects_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_objects_proto_rawDesc), len(file_carabiner_core_v1_objects_proto_rawDesc)))
	})
	return file_carabiner_core_v1_objects_proto_rawDescData
}

var file_carabiner_core_v1_objects_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_carabiner_core_v1_objects_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_carabiner_core_v1_objects_proto_goTypes = []any{
	(Status)(0),        // 0: carabiner.core.v1.Status
	(*System)(nil),     // 1: carabiner.core.v1.System
	(*Namespace)(nil),  // 2: carabiner.core.v1.Namespace
	(*Repository)(nil), // 3: carabiner.core.v1.Repository
	(*Pipeline)(nil),   // 4: carabiner.core.v1.Pipeline
	(*Step)(nil),       // 5: carabiner.core.v1.Step
}
var file_carabiner_core_v1_objects_proto_depIdxs = []int32{
	1, // 0: carabiner.core.v1.Namespace.system:type_name -> carabiner.core.v1.System
	0, // 1: carabiner.core.v1.Namespace.status:type_name -> carabiner.core.v1.Status
	2, // 2: carabiner.core.v1.Repository.namespace:type_name -> carabiner.core.v1.Namespace
	3, // 3: carabiner.core.v1.Pipeline.repository:type_name -> carabiner.core.v1.Repository
	4, // 4: carabiner.core.v1.Step.pipeline:type_name -> carabiner.core.v1.Pipeline
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_carabiner_core_v1_objects_proto_init() }
func file_carabiner_core_v1_objects_proto_init() {
	if File_carabiner_core_v1_objects_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_carabiner_core_v1_objects_proto_rawDesc), len(file_carabiner_core_v1_objects_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_carabiner_core_v1_objects_proto_goTypes,
		DependencyIndexes: file_carabiner_core_v1_objects_proto_depIdxs,
		EnumInfos:         file_carabiner_core_v1_objects_proto_enumTypes,
		MessageInfos:      file_carabiner_core_v1_objects_proto_msgTypes,
	}.Build()
	File_carabiner_core_v1_objects_proto = out.File
	file_carabiner_core_v1_objects_proto_goTypes = nil
	file_carabiner_core_v1_objects_proto_depIdxs = nil
}
